<?php
	require_once('functions.php');
	require_once('read.php');
	require_once('login_functions.php');
	require_once('sessions.php');
	require_once('send_mail.php');
	require_once('crud_user.php');
	require_once('addmovie.php');
	require_once('delmovie.php');
	require_once('updatemovie.php');
	require_once('single_edit_form.php');
?>